#! /bin/sh
# installation that needed to work on workspaces using clang++14
#

wget https://apt.llvm.org/llvm.sh
echo "just download llvm"
chmod +x llvm.sh
echo "llvm is now excutable"
sh llvm.sh 14 -y
echo "running llvm"
set timeout 2
echo "removing llvm"
rm llvm.sh
echo "finish"